# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ca2a8d274869a21805989c683e6dc9c6f4ac410090fc51f2fdf3b6b4c9a2e1466a49483d5344c6f6e447f1ba4ca2ff0dd52d25fc624d9c5776f0d64fe7fbaee

test:
  secret_key_base: fef09e691847956ceeae0c0a518d9168f19ef8a23f1887d22eb5fbd856f139ff9e9f2865c8362ced539ded3740abd975b5920a30a3cce9d7f0944a588dd5d5fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
